---
- name: Get Device Info
  hosts: switch_name
  connection: netconf
  vars:
    ansible_network_os: junipernetworks.junos.junos
  vars_prompt:
    - name: chg_number
      prompt: "Please Enter the CHG number"
      private: no

  tasks:
    - name: Determine If Current Device Is Supported
      junos_command:
        commands:
        - "show version"
      register: result

    - name: Get Output
      set_fact:
        device_model: "{{ (result.stdout[0] | parse_cli_textfsm('./textfsm/device_model.textfsm'))[0].deviceModel }}"

    - name: Print Device Model
      debug:
        var: device_model

    - name: Unsupported Model
      fail: 
        msg: "Unsupported Model"
      when: "'qfx5200' not in device_model"

    - name: Get Host Links
      import_tasks: GetInfo/host_links.yaml

    - name: Generate Host Links Management Procedure
      import_tasks: Procedure/host_links_management.yaml

    - name: Get Device Config
      import_tasks: GetInfo/device_config.yaml

    - name: Get Uplinks Group 
      import_tasks: GetInfo/uplinks_group.yaml

    - name: Generate Preparation Procedure
      import_tasks: Procedure/preparation.yaml

    - name: Generate Uplinks Management Procedure
      import_tasks: Procedure/uplinks_management.yaml

    - name: Generate Plans
      import_tasks: Post/plans.yaml

    - name: Post request
      import_tasks: Post/request.yaml
